# Generated by Django 5.2.3 on 2025-06-30 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date du créneau')),
                ('heure_debut', models.TimeField(help_text='Heure de début du créneau')),
                ('heure_fin', models.TimeField(help_text='Heure de fin du créneau')),
                ('max_personnes', models.PositiveIntegerField(default=3, help_text='Nombre maximum de personnes autorisées pour ce créneau')),
                ('actif', models.BooleanField(default=True, help_text='Créneau disponible pour inscription')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('date', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='HoraireOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (0=Lundi, 6=Dimanche)')),
                ('heure_ouverture', models.TimeField(help_text="Heure d'ouverture")),
                ('heure_fermeture', models.TimeField(help_text='Heure de fermeture')),
                ('actif', models.BooleanField(default=True, help_text='Horaire actif')),
            ],
            options={
                'verbose_name': "Horaire d'ouverture",
                'verbose_name_plural': "Horaires d'ouverture",
                'ordering': ['jour_semaine', 'heure_ouverture'],
                'unique_together': {('jour_semaine',)},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'inscription")),
                ('annulee', models.BooleanField(default=False, help_text='Inscription annulée')),
                ('date_annulation', models.DateTimeField(blank=True, help_text="Date et heure d'annulation", null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire optionnel')),
                ('creneau', models.ForeignKey(help_text='Créneau horaire', on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='permanences.creneauhoraire')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur inscrit', on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('utilisateur', 'creneau')},
            },
        ),
    ]
